package se.sics.kompics.testkit;

import se.sics.kompics.*;
import se.sics.kompics.testkit.fsm.EventQueue;
import se.sics.kompics.testkit.fsm.FSM;
import se.sics.kompics.testkit.scheduler.CallingThreadScheduler;

import java.util.Map;

public class Proxy<T extends ComponentDefinition> extends ComponentDefinition{

  private final EventQueue eventQueue = new EventQueue();
  private PortConfig portConfig;
  private Component cut;
  private T definitionUnderTest;
  private FSM<T> fsm;

  Proxy() {
    getComponentCore().setScheduler(new CallingThreadScheduler());
  }

  T createComponentUnderTest(
          Class<T> definition, Init<T> initEvent) {
    cut = create(definition, initEvent);
    init();
    return definitionUnderTest;
  }

  T createComponentUnderTest(
          Class<T> definition, Init.None initEvent) {
    cut = create(definition, initEvent);
    init();
    return definitionUnderTest;
  }

  @SuppressWarnings("unchecked")
  private void init() {
    createPortConfig();
    definitionUnderTest = (T) cut.getComponent();
    fsm = new FSM<T>(this, definitionUnderTest);
  }

  FSM<T> getFsm() {
    return fsm;
  }

  Component getComponentUnderTest() {
    return cut;
  }

  public EventQueue getEventQueue() {
    return eventQueue;
  }

  <T extends ComponentDefinition> Component createSetupComponent(Class<T> cClass, Init<T> initEvent) {
    Component c = create(cClass, initEvent);
    setupComponent(c);
    return c;
  }

  <T extends ComponentDefinition> Component createSetupComponent(Class<T> cClass, Init.None initEvent) {
    Component c = create(cClass, initEvent);
    setupComponent(c);
    return c;
  }

  <P extends PortType> Negative<P> providePort(Class<P> portType) {
    return provides(portType);
  }

  <P extends PortType> Positive<P> requirePort(Class<P> portType) {
    return requires(portType);
  }

  private Handler<Start> startHandler = new Handler<Start>() {
    @Override
    public void handle(Start event) { }
  };

  private void setupComponent(Component c) {
    // only proxy is scheduled on calling thread
    c.getComponent().getComponentCore().setScheduler(null);
  }

  {
    subscribe(startHandler, control);
  }

  private void createPortConfig() {
    portConfig = new PortConfig(this);
  }

  Map<Class<? extends PortType>, JavaPort<? extends PortType>> getCutPositivePorts() {
    return ((JavaComponent) cut).positivePorts;
  }

  Map<Class<? extends PortType>, JavaPort<? extends PortType>> getCutNegativePorts() {
    return ((JavaComponent) cut).negativePorts;
  }

  <P extends PortType> void doConnect(
          Positive<P> positive, Negative<P> negative, ChannelFactory factory) {
    portConfig.doConnect(positive, negative, factory);
  }

  boolean isConnectedPort(Port<? extends PortType> port) {
    return portConfig.isConnectedPort(port);
  }

  @Override
  public Fault.ResolveAction handleFault(Fault fault) {
    if (fault.getSource().getComponentCore() != cut) {
      Testkit.logger.error("Fault not belonging to test component was escalated");
      // assert faults only generated by cut
      return Fault.ResolveAction.ESCALATE;
    }
    // sync with fsm
    ExpectedFault expectedFault = fsm.getNextExpectedFault();

    if (expectedFault == null) {
      Testkit.logger.error("Unexpected fault was escalated: No matching state was found");
      return Fault.ResolveAction.ESCALATE;
    }

    return expectedFault.matchFault(fault);
  }

}
